# This is a basic workflow to help you get started with Actions

name: New Version

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install Playdate SDK
        id: playdate
        uses: pd-rs/get-playdate-sdk@0.1.2
        with:
            # optional, can be omitted
            # possible values: version (1.10.0 or 1.9.3) or "latest"
            version: latest
      - name: usage
        run: |
          echo "SDK root: $PLAYDATE_SDK_PATH"
          echo "SDK root: ${{ steps.playdate.outputs.root }}"
          echo "SDK version: ${{ steps.playdate.outputs.version }}"
          pdc --version
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          pdc ./ ./build
          ls
