name: Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Install the Playdate SDK
        id: playdate
        uses: pd-rs/get-playdate-sdk@0.1.2
        with:
            version: latest
      - name: Build the Project
        run: |
          pdc -k ./ ./build
      - name: Upload the build
        uses: actions/upload-artifact@v3
        with:
          name: Build
          path: ./build.pdx
