name: New version

# permissions: write-all

# Controls when the workflow will run
on:
  push:
    paths:
      - 'version.txt'
      - '.github/workflows/new_version.yml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      - name: Install the Playdate SDK
        id: playdate
        uses: pd-rs/get-playdate-sdk@0.1.2
        with:
            # possible values: version (1.10.0 or 1.9.3) or "latest"
            version: latest
      - name: Build the Project
        run: |
          pdc -k ./ ./build
#       - name: Zip build
#         uses: montudor/action-zip@v1
#         with:
#           args: zip -qq -r Build.zip build.pdx
      - name: Read version file
        id: versionfile
        uses: juliangruber/read-file-action@v1
        with:
          path: ./version.txt
      - name: Read build num
        id: versionnum
        uses: juliangruber/read-file-action@v1
        with:
          path: ./buildnum.txt
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%d-%m-%Y')"
      - name: Create a new tag
        uses: negz/create-tag@v1
        with:
          version: v${{ steps.versionfile.outputs.content }}.${{ steps.versionnum.outputs.content }}
          message: Automatic release from ${{ steps.date.outputs.date }}
          token: ${{ secrets.GITHUB_TOKEN }}
#       - name: Update the latest tag
#         uses: EndBug/latest-tag@latest
#         with:
#           # You can change the name of the tag with this input.
#           # Default: 'latest'
#           tag-name: latest
#       - name: Release & Assets
#         # You may pin to the exact commit or the version.
#         # uses: Hs1r1us/Release-AIO@354b8db50d5b6310b621cb6c5e29d1f8e611aff7
#         uses: Hs1r1us/Release-AIO@v1.0
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         with:
#           # The name of the tag
#           tag_name: latest
#           # The name of the release
#           release_name: v${{ steps.versionfile.outputs.content }}.${{ steps.versionnum.outputs.content }}
#           # Text describing the contents of the tag
#           body: Automatic release from ${{ steps.date.outputs.date }}
#           # The path to the asset you want to upload
#           asset_files: Build.zip
#           # `true` to identify the release as a prerelease. `false` to identify the release as a full release. Default: `false`
#           prerelease: true
