name: Remove old artifacts

on:
  workflow_dispatch:
  schedule:
    # Every week at 4am on Sunday
    - cron: '0 4 * * 0'

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        age: '7 days' # '<number> <unit>', e.g. 5 days, 2 years, 90 seconds, parsed by Moment.js
        # Optional inputs
        # skip-tags: true
        skip-recent: 1
